version: '3.1'
services:
  web:
    build: .
    ports:
     - '8080:8080'
    links:
      - 'mysql'
    restart: on-failure
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blog
      - MYSQL_USER=go
      - MYSQL_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql:/var/lib/mysql
